import os 
import time

def credits():
    os.system("cls")
    time.sleep(1)    
    print(" _______________________________________________________________________")
    print("|[] Credits                                                       |F]|!|")
    print("|--------------------------------------------------------------------|-|")
    print("|12.Workbench:> Credits.py                                           | |")
    print("|Loading...                                                          | |")
    print("|                                                                    | |")
    print("|                                                                    |_|")
    print("|____________________________________________________________________|/|")
    time.sleep(2)     
    os.system("cls")                                                                                                                          
    print("                                                                                        bbbbbbbb           "        )               
    print("        GGGGGGGGGGGGG                                                                   b::::::b                        ")          
    print("     GGG::::::::::::G                                                                   b::::::b                                  ")
    print("   GG:::::::::::::::G                                                                   b::::::b                                  ")
    print("  G:::::GGGGGGGG::::G                                                                    b:::::b                                  ")
    print(" G:::::G       GGGGGG  aaaaaaaaaaaaa      mmmmmmm    mmmmmmm       eeeeeeeeeeee          b:::::bbbbbbbbb yyyyyyy           yyyyyyy")
    print("G:::::G                a::::::::::::a   mm:::::::m  m:::::::mm   ee::::::::::::ee        b::::::::::::::bby:::::y         y:::::y ")
    print("G:::::G                aaaaaaaaa:::::a m::::::::::mm::::::::::m e::::::eeeee:::::ee      b::::::::::::::::by:::::y       y:::::y  ")
    print("G:::::G    GGGGGGGGGG           a::::a m::::::::::::::::::::::me::::::e     e:::::e      b:::::bbbbb:::::::by:::::y     y:::::y   ")
    print("G:::::G    G::::::::G    aaaaaaa:::::a m:::::mmm::::::mmm:::::me:::::::eeeee::::::e      b:::::b    b::::::b y:::::y   y:::::y   ") 
    print("G:::::G    GGGGG::::G  aa::::::::::::a m::::m   m::::m   m::::me:::::::::::::::::e       b:::::b     b:::::b  y:::::y y:::::y     ")
    print("G:::::G        G::::G a::::aaaa::::::a m::::m   m::::m   m::::me::::::eeeeeeeeeee        b:::::b     b:::::b   y:::::y:::::y      ")
    print(" G:::::G       G::::Ga::::a    a:::::a m::::m   m::::m   m::::me:::::::e                 b:::::b     b:::::b    y:::::::::y       ")
    print("  G:::::GGGGGGGG::::Ga::::a    a:::::a m::::m   m::::m   m::::me::::::::e                b:::::bbbbbb::::::b     y:::::::y     ")   
    print("   GG:::::::::::::::Ga:::::aaaa::::::a m::::m   m::::m   m::::m e::::::::eeeeeeee        b::::::::::::::::b       y:::::y     ")    
    print("     GGG::::::GGG:::G a::::::::::aa:::am::::m   m::::m   m::::m  ee:::::::::::::e        b:::::::::::::::b       y:::::y        ")  
    print("        GGGGGG   GGGG  aaaaaaaaaa  aaaammmmmm   mmmmmm   mmmmmm    eeeeeeeeeeeeee        bbbbbbbbbbbbbbbb       y:::::y         ")  
    print("                                                                                                               y:::::y      ")      
    print("                                                                                                              y:::::y        ")     
    print("                                                                                                             y:::::y              ")
    print("                                                                                                            y:::::y         ")      
    print("                                                                                                           yyyyyyy                ")
    print("\n")
    time.sleep(2)
    os.system("cls")
    print("      ___           ___           ___       ___           ___                    ___                       ___       ___ ")
    print("     /\__\         /\  \         /\__\     /\  \         |\__\                  /\__\          ___        /\__\     /\__\ ")
    print("    /:/  /        /::\  \       /:/  /    /::\  \        |:|  |                /:/  /         /\  \      /:/  /    /:/  /")
    print("   /:/__/        /:/\:\  \     /:/  /    /:/\:\  \       |:|  |               /:/__/          \:\  \    /:/  /    /:/  / ")
    print("  /::\  \ ___   /::\~\:\  \   /:/  /    /::\~\:\  \      |:|__|__            /::\  \ ___      /::\__\  /:/  /    /:/  /  ")
    print(" /:/\:\  /\__\ /:/\:\ \:\__\ /:/__/    /:/\:\ \:\__\     /::::\__\          /:/\:\  /\__\  __/:/\/__/ /:/__/    /:/__/   ")
    print(" \/__\:\/:/  / \/__\:\/:/  / \:\  \    \:\~\:\ \/__/    /:/~~/~             \/__\:\/:/  / /\/:/  /    \:\  \    \:\  \   ")
    print("      \::/  /       \::/  /   \:\  \    \:\ \:\__\     /:/  /                    \::/  /  \::/__/      \:\  \    \:\  \  ")
    print("      /:/  /        /:/  /     \:\  \    \:\ \/__/     \/__/                     /:/  /    \:\__\       \:\  \    \:\  \ ")
    print("     /:/  /        /:/  /       \:\__\    \:\__\                                /:/  /      \/__/        \:\__\    \:\__\ ")
    print("     \/__/         \/__/         \/__/     \/__/                                \/__/                     \/__/     \/__/")
    time.sleep(3)
    os.system("cls")
    print("\n\n\n\n\n\n\t\t\t\t\tAnimations by Andrew M. Evans\n\n\n\n\n")
    time.sleep(2)
    os.system("cls")
    print("\n\n\n\n\n\n\t\t\t\t\t\t\t:)\n\n\n\n\n")
    time.sleep(.5)
    os.system("cls")
    print("\n\n\n\n\n\n\t\t\t\t\tThank you\n")
    time.sleep(.4)
    print("\t\t\t\t\tfor\n")
    time.sleep(.4)
    print("\t\t\t\t\tPlaying\n\n\n\n\n")
    time.sleep(2)
credits()
